config/routes.rb
OpenPalette::Application.routes.draw do

  match '/contact', :to => 'pages#contact' 
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'   

  
  resources :users do
    member do
      get :following, :followers, :hearts
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :posts do #,    :only => [:create, :destroy, :show,:edit,:new]
    member do
      get :tag
    end
  end
  resources :pages do #,    :only => [:create, :destroy, :show,:edit,:new]
    member do
      get :tag
    end
  end
  resources :relationships, :only => [:create, :destroy]
  resources :hearts, :only => [:create, :destroy]  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match "/auth/:provider/callback" => "sessions#create"
  match '/auth/failure' => 'sessions#failure'

   root :to => "posts#index"

end

app/views/shared/_edit_post.html.haml
#edit-post-modal.modal.hide.fade
  = render 'shared/edit_post_form'

app/views/shared/_edit_post_form.html.haml
= form_for @post, :html=>{:multipart =>true}, :remote=>true do |f|
  .modal-header 
    %a.close{:href=>"#"} &times;
    %h3 Edit Post
  .modal-body                           
    = render 'shared/error_messages', :object => f.object
    .clearfix
      = f.label :title
      .input
        = f.text_field :title
    .clearfix
      .input
        = f.file_field :image
    .clearfix
      = f.label :remote_image_url, "or image URL:"
      .input
        = f.text_field :remote_image_url
    .clearfix
      = f.label :content, "Description"
      .input
        = f.text_area :content, :class=>"xlarge", :rows=>"3"
        .help-block Provide a description for your picture. 
    .clearfix
      = f.label :tag_list, "Tags"
      .input
        = f.text_field :tag_list
        .help-block Tags help categorize the posts. Separate tags with commas. 
  .modal-footer
    = f.submit "Submit", :class=>"btn primary"
    = f.submit "Cancel", :class=>"btn"

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  - object.errors.full_messages.each do |msg|
    .alert-message.fade.in.error{:"data-alert"=>"alert"}
      %p
        = msg
                          
                                                            

app/views/shared/_feed_posts.html.haml
- unless @posts.empty?
  - if @title
    %h2 
      = @title
  %ul.media-grid.posts
    - for post in @posts
      = render :partial => "shared/feed_item", :locals => { :feed_item => post}
    
- else
  %p No Posts!

app/views/shared/_following.html.haml
- if @user
  %ul.media-grid
    - @user.following.popular.each do |u|
      %li 
        = link_to gravatar_for(u, :size => 48, :class => "thumbnail", :alt => u.name), user_path(u), :title=> "#{u.name}", :class=>"user"                                             

app/views/shared/_hearters.html.haml
- if @hearters
  %ul.media-grid
    - @hearters.each do |u|
      %li 
        = link_to gravatar_for(u, :size => 48, :class => "thumbnail", :alt => u.name), user_path(u)

app/views/shared/_hearts.html.haml
- if @user
  %ul.media-grid.posts
    - @user.hearts.limit(9).each do |heart|       
      - post = heart.hearted
      %li 
        = link_to image_tag(post.image_url(:thumb).to_s, :alt=> post.title,:class => "thumbnail", :alt=> post.title),post_path(post),:class=>"post"
                                                

app/views/shared/_settings.html.haml
#settings-modal.modal.hide.fade
  = render 'shared/settings_form'

app/views/shared/_settings_form.html.haml
= form_for(@user, :remote => true) do |f|
  .modal-header 
    %a.close{:href=>"#"} &times;
    %h3 Settings
  .modal-body
    = render 'shared/error_messages', :object => f.object
    .clearfix
      = f.label :name
      .input
        = f.text_field :name
    .clearfix
      = f.label :email
      .input
        = f.text_field :email
    .clearfix
      = f.label :password
      .input
        = f.password_field :password
    .clearfix
      = f.label :password_confirmation, "Confirmation"
      .input
        = f.password_field :password_confirmation
    .modal-footer
      = f.submit "Save Changes", :class=>"btn primary"
      = f.submit "Cancel", :class=>"btn"

app/views/shared/_signin_modal_form.haml
= form_for(:session, :url => sessions_path, :remote=>true) do |f|
  .modal-header 
    %a.close{:href=>"#"} &times;
    %h3 Sign In
  .modal-body                           
    - flash.each do |key, value|
      .clearfix
        .alert-message.fade.in{:"data-alert"=>"alert", :class=> key}
          %p
            = value
    .clearfix
      = f.label :email
      .input
        = f.text_field :email
    .clearfix
      = f.label :password
      .input
        = f.password_field :password
  .modal-footer
    = f.submit "Sign in", :class=>"btn primary"
    = f.submit "Cancel", :class=>"btn"            

app/views/shared/_signup_message.html.haml
- unless signed_in?
  .hero-unit
    %h2 Welcome to the Open Palette Beta
    %p Open Palette is framework for niche communities. It is currently under active development.
    %p Join today to help out with testing!                                                                                                                                   
    %p
      = link_to "Sign up »", signup_path, :class=>"btn primary large"

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats buttons">
     <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
     </a>
     <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
     </a>
     <a href="<%= hearts_user_path(@user) %>">
          <span id="hearts" class="stat">
            <%= pluralize(@user.hearts.count, "hearts") %>
          </span>
     </a>
     <a href="<%= user_path(@user) %>">
        <span class="posts">
           <%= pluralize(@user.posts.count, "post") %>
         </span>
     </a>             
</div>

app/views/shared/_table_user.html.erb
<tr>
   <td class="user">
      <%= gravatar_for table_user, :size => 30 %>
      <%= link_to table_user.name, table_user %>
   </td>
   <td class="num posts">
      <%= link_to table_user.posts.count, table_user %>
   </td>
   <td class="num hearts">
      <%= link_to table_user.hearts.count, hearts_user_path(table_user) %>
   </td>
   <td class="num follows">
      <%= link_to table_user.following.count, following_user_path(table_user) %>
   </td>
   <td class="num followers">
      <%= link_to table_user.followers.count, followers_user_path(table_user) %>
   </td>    
   <td class="follow"> 

      <% unless current_user?(table_user) %>
        <% if current_user.following?(table_user) %>
          <%= link_to "unfollow", { :id=>table_user.id, :controller => :relationships, :action => "destroy"},:method=>:delete, :"data-followed-id"=>table_user.id, :remote => true %>
        <% else %>
          <%= link_to "follow", { :id=>table_user.id, :controller => :relationships, :action => "create"},:method=>:post, :"data-followed-id"=>table_user.id, :remote => true %>
        <% end %>
      <% end %>
   </td>
   
</tr>

app/views/shared/_top_users.html.haml
%h5 Top Users
%ul.media-grid
  - User.popular.each do |u|
    %li 
      = link_to gravatar_for(u, :size => 48, :class => "thumbnail", :alt => u.name), user_path(u), :title=> "#{u.name}", :class=>"user"