config/routes.rb
OpenPalette::Application.routes.draw do

  match '/contact', :to => 'pages#contact' 
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'   

  
  resources :users do
    member do
      get :following, :followers, :hearts
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :posts do #,    :only => [:create, :destroy, :show,:edit,:new]
    member do
      get :tag
    end
  end
  resources :pages do #,    :only => [:create, :destroy, :show,:edit,:new]
    member do
      get :tag
    end
  end
  resources :relationships, :only => [:create, :destroy]
  resources :hearts, :only => [:create, :destroy]  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match "/auth/:provider/callback" => "sessions#create"
  match '/auth/failure' => 'sessions#failure'

   root :to => "posts#index"

end

app/views/layouts/_footer.html.haml
%footer
  %p 
    © Open Palette 2011 by 
    %a{:href=>"http://zadell.com"} Zac
    
               

app/views/layouts/_header.html.haml
%header.topbar
  .topbar-inner
    .container                                
      = link_to "Open Palette", root_path, :class=>"brand" 
      - @current_controller = params[:controller]
      - @current_action = params[:action]
      - @current_id = params[:id]
      %ul.nav
        - if signed_in?
          - if @current_controller == "posts" && @current_action == "index"
            %li.alt-icon.home.active
              = link_to 'Home', root_path
          - else
            %li.alt-icon.home
              = link_to 'Home', root_path
      %ul.nav.secondary-nav
        - unless signed_in?
          %li
            = link_to "Sign in", signin_path, :id => 'signin-link', :"data-controls-modal" => "signin-modal", :"data-keyboard"=>"true", :"data-backdrop"=>"true"
        - else
          %li.alt-icon.add-alt
            = link_to "Post", new_post_path, :id => 'post-link', :"data-controls-modal" => "post-modal", :"data-keyboard"=>"true",:"data-backdrop"=>"true",:title => "Post a new picture!", :rel => "twipsy"                                                         
          %li
            .vr
          %li.dropdown{:data => {:dropdown=>"dropdown"}}
            %a.dropdown-toggle{:href=> "#"}
              = current_user.name
            %ul.dropdown-menu
              %li
                = link_to 'Users', users_path
              
              %li
                = link_to 'Favorites', hearts_user_path(current_user)
              %li
                = link_to 'Profile', current_user
              %li.divider
              %li
                = link_to 'Settings', edit_user_path(current_user), :id => 'settings-link', :"data-controls-modal" => "settings-modal", :"data-keyboard"=>"true", :"data-backdrop"=>"true"
              %li
                = link_to "Sign out", signout_path, :method => :delete
                                                              

app/views/layouts/application.html.haml
!!! Strict                                
%html
  %head
    %title 
      = title
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Pacifico"
    = javascript_include_tag "application"
  %body
    = render 'layouts/header'
    = yield
    = render 'shared/signin_modal'
    - if signed_in?
      - @user = current_user
      = render 'shared/upload'
      = render 'shared/settings'